[package]
name = "dedupe_files"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake2  = "0.10.4"
clap    = { version = "3.1.10", features = ["derive"] }
core_affinity = "0.5.10"
